[package]
name = "chasm"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "chasm"
path = "src/main.rs"

[dependencies]
clap = "3.1.6"
libc = "0.2.121"
